version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./docker/phpmyadmin:/etc/phpmyadmin/config.user.inc.php
